[build]
  base = "web"
  command = "npm install && npm run build"
  publish = "web/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
